export default {
    User: [
      {
        user_id: 1,
        name: "인성",
        img:"../../images/profile.png",
        created_at: "2018-09-11"
      },
      {
        user_id: 2,
        name: "탁우",
        img:"../../images/profile.png",
        created_at: "2018-09-12"
      },
      {
        user_id: 3,
        name: "준우",
        img:"../../images/profile.png",
        created_at: "2018-09-13"
      },
      {
        user_id: 4,
        name: "채우",
        img:"../../images/profile.png",
        created_at: "2018-09-14"
      },
      {
        user_id: 5,
        name: "예나",
        img:"../../images/profile.png",
        created_at: "2018-09-15"
      }
    ],
    Expert: [
      {
        expert_id: 1,
        name: "김상헌",
        content: '안녕하세요', 
        major: '야구응원댄스',
        awards:'KBO 우수단장상',
        sns:'없음',
        company:'허니크루',
        img:"../../images/expert_1.png",
        created_at: "2020-09-15"
      },
      {
        expert_id: 2,
        name: "구자욱",
        content: '안녕하세요', 
        major: '좌익수',
        awards:'KBO 신인상',
        sns:'없음',
        company:'삼성라이온즈',
        img:"../../images/expert_1.png",
        created_at: "2020-09-15"
      },
      {
        expert_id: 3,
        name: "상수",
        content: '안녕하세요', 
        major: '유격수',
        awards:'KBO 최다도루상',
        sns:'없음',
        company:'삼성라이온즈',
        img:"../../images/expert_1.png",
        created_at: "2020-09-15"
      },
      {
        expert_id: 4,
        name: "헌곤",
        content: '안녕하세요', 
        major: '우익수',
        awards:'KBO 최다홈런상',
        sns:'없음',
        company:'삼성라이온즈',
        img:"../../images/expert_1.png",
        created_at: "2020-09-15"
      }
    ],
    Content: [
      {
        content_id: 1,
        user_id: 5,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-15",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 2,
        user_id: 1,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-11",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 3,
        user_id: 3,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-12",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 4,
        user_id: 2,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-13",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 5,
        user_id: 4,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-14",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 6,
        user_id: 5,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-15",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 7,
        user_id: 1,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-11",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 8,
        user_id: 3,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-12",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 9,
        user_id: 2,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-13",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 10,
        user_id: 4,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-14",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 11,
        user_id: 5,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-15",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 12,
        user_id: 1,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-11",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 13,
        user_id: 3,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-12",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 14,
        user_id: 2,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-13",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"알려드릴 것이 없습니다. 하산하세요",
        updated_at: "2020-05-09",
      },
      {
        content_id: 15,
        user_id: 4,
        title: "게시판 제목",
        context: "게시판 내용",
        created_at: "2020-09-14",
        updated_at: null,
        reply: false,
        expert_id: 1,
        reply_context: null,
        updated_at: "2020-05-09",
      },
      {
        content_id: 16,
        user_id: 5,
        title: "안녕하세요. 상헌 전문가님",
        context: "안녕하세요. 김상수 선수 응원가 안무 연습 중인데요, 삼성의 승리를 위해 안타안타~ 하는 부분이 어려워요.. ",
        created_at: "2020-09-15",
        updated_at: null,
        reply: true,
        expert_id: 1,
        reply_context:"네, 안녕하세요. 피드백 신청 감사합니다. 말씀해 주신 부분은 팔을 곧게 펴고 추는 게 좋습니다.",
        updated_at: "2020-05-09",
      }
    ],
  };
  